In [1]:
import os
import sys
# import re
import pickle
from collections import defaultdict, OrderedDict, Counter
import warnings
warnings.filterwarnings('ignore')

from tqdm import tqdm

In [2]:
import numpy as np
import pandas as pd
# from pandas.plotting import scatter_matrix
# from pandas_profiling import ProfileReport
# from missingno import dendrogram
# import missingno as msno

# pd.options.display.float_format = '{:0.5f}'.format`

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns

# settings for seaborn plot sizes
sns.set(rc={'figure.figsize':(20, 10)})
plt.rc('font',family='Malgun Gothic')

In [4]:
def percent_(df_bin, df) :
    total = sum(df_bin)
    #print(total)
    percentage = df_bin/total*100
    #print(percentage)
    df['%']=percentage
    ## 데이터프레임의 항목당 백분율 계산 함수 (매개변수 (DF_백분율로 나타내려는 column, DF))

In [6]:
data=pd.read_csv('data/국민기초생활보장_수급자_20221122191635.csv', encoding='euc-kr')

In [7]:
data

       시점 시군별(1) 시군별(2) 수급자별(1)     수급자별(2)   수급자별(3)     데이터
0    2018     합계     소계   총 수급자    가구수 (가구)        소계  198442
1    2018     합계     소계   총 수급자      인원 (명)        소계  297009
2    2018     합계     소계   총 수급자      인원 (명)         남  132790
3    2018     합계     소계   총 수급자      인원 (명)         여  164219
4    2018     합계     소계   일반수급자    가구수 (가구)        소계  192798
..    ...    ...    ...     ...         ...       ...     ...
539  2018     북부    가평군   특례수급자   개인단위보장 특례    인원 (명)     ...
540  2018     북부    가평군   특례수급자  타법령에 의한 특례  가구수 (가구)     ...
541  2018     북부    가평군   특례수급자  타법령에 의한 특례    인원 (명)     ...
542  2018     북부    가평군   시설수급자     시설수 (개)        소계      21
543  2018     북부    가평군   시설수급자      인원 (명)        소계    1167

[544 rows x 7 columns]

In [8]:
data.head(50)

      시점 시군별(1) 시군별(2) 수급자별(1)     수급자별(2)   수급자별(3)     데이터
0   2018     합계     소계   총 수급자    가구수 (가구)        소계  198442
1   2018     합계     소계   총 수급자      인원 (명)        소계  297009
2   2018     합계     소계   총 수급자      인원 (명)         남  132790
3   2018     합계     소계   총 수급자      인원 (명)         여  164219
4   2018     합계     소계   일반수급자    가구수 (가구)        소계  192798
5   2018     합계     소계   일반수급자      인원 (명)        소계  273930
6   2018     합계     소계   일반수급자      인원 (명)         남  123566
7   2018     합계     소계   일반수급자      인원 (명)         여  150364
8   2018     합계     소계   특례수급자    가구수 (가구)        소계    5644
9   2018     합계     소계   특례수급자      인원 (명)        소계    7495
10  2018     합계     소계   특례수급자   개인단위보장 특례  가구수 (가구)     ...
11  2018     합계     소계   특례수급자   개인단위보장 특례    인원 (명)     ...
12  2018     합계     소계   특례수급자  타법령에 의한 특례  가구수 (가구)     ...
13  2018     합계     소계   특례수급자  타법령에 의한 특례    인원 (명)     ...
14  2018     합계     소계   시설수급자     시설수 (개)        소계    1611
15  2018     합계     소계   시설수급자      인원 (명)        소계   15584
16  2018     남부     소계   총 수급자    가구수 (가구)        소계  133772
17  2018     남부     소계   총 수급자      인원 (명)        소계  197752
18  2018     남부     소계   총 수급자      인원 (명)         남   88461
19  2018     남부     소계   총 수급자      인원 (명)         여  109291
20  2018     남부     소계   일반수급자    가구수 (가구)        소계  129613
21  2018     남부     소계   일반수급자      인원 (명)        소계  183245
22  2018     남부     소계   일반수급자      인원 (명)         남   82786
23  2018     남부     소계   일반수급자      인원 (명)         여  100459
24  2018     남부     소계   특례수급자    가구수 (가구)        소계    4159
25  2018     남부     소계   특례수급자      인원 (명)        소계    5509
26  2018     남부     소계   특례수급자   개인단위보장 특례  가구수 (가구)     ...
27  2018     남부     소계   특례수급자   개인단위보장 특례    인원 (명)     ...
28  2018     남부     소계   특례수급자  타법령에 의한 특례  가구수 (가구)     ...
29  2018     남부     소계   특례수급자  타법령에 의한 특례    인원 (명)     ...
30  2018     남부     소계   시설수급자     시설수 (개)        소계     956
31  2018     남부     소계   시설수급자      인원 (명)        소계    8998
32  2018     남부    수원시   총 수급자    가구수 (가구)        소계   14344
33  2018     남부    수원시   총 수급자      인원 (명)        소계   20478
34  2018     남부    수원시   총 수급자      인원 (명)         남    9263
35  2018     남부    수원시   총 수급자      인원 (명)         여   11215
36  2018     남부    수원시   일반수급자    가구수 (가구)        소계   13889
37  2018     남부    수원시   일반수급자      인원 (명)        소계   19082
38  2018     남부    수원시   일반수급자      인원 (명)         남    8746
39  2018     남부    수원시   일반수급자      인원 (명)         여   10336
40  2018     남부    수원시   특례수급자    가구수 (가구)        소계     455
41  2018     남부    수원시   특례수급자      인원 (명)        소계     583
42  2018     남부    수원시   특례수급자   개인단위보장 특례  가구수 (가구)     ...
43  2018     남부    수원시   특례수급자   개인단위보장 특례    인원 (명)     ...
44  2018     남부    수원시   특례수급자  타법령에 의한 특례  가구수 (가구)     ...
45  2018     남부    수원시   특례수급자  타법령에 의한 특례    인원 (명)     ...
46  2018     남부    수원시   시설수급자     시설수 (개)        소계      69
47  2018     남부    수원시   시설수급자      인원 (명)        소계     813
48  2018     남부    성남시   총 수급자    가구수 (가구)        소계   16598
49  2018     남부    성남시   총 수급자      인원 (명)        소계   23921

In [14]:
data_1=data[data['수급자별(1)'] == '총 수급자']

In [17]:
data_2=data_1[data_1['수급자별(3)']=='소계']

In [22]:
data_3=data_2[data_2['수급자별(2)'] == '인원 (명)']

In [25]:
data_4=data_3[data_3['시군별(2)'] != '소계']

In [28]:
data_5=data_4[['시군별(2)','데이터']]

In [32]:
data_5

    시군별(2)    데이터
33     수원시  20478
49     성남시  23921
65     안양시  10238
81     부천시  19370
97     광명시   7730
113    평택시  12286
129    안산시  22637
145    과천시    962
161    오산시   4326
177    시흥시   9710
193    군포시   6449
209    의왕시   2581
225    하남시   4258
241    용인시  10557
257    이천시   5010
273    안성시   5613
289    김포시   7866
305    화성시   9442
321    광주시   5882
337    여주시   4567
353    양평군   3869
385   의정부시  15633
401   동두천시   5388
417    고양시  23335
433    구리시   6116
449   남양주시  16046
465    파주시  13080
481    양주시   7396
497    포천시   6121
513    연천군   2599
529    가평군   3543

In [34]:
data_5.rename(columns={'시군별(2)':'지역','데이터':'기초수급자 수'}, inplace=True)

In [38]:
data_5

       지역 기초수급자 수
33    수원시   20478
49    성남시   23921
65    안양시   10238
81    부천시   19370
97    광명시    7730
113   평택시   12286
129   안산시   22637
145   과천시     962
161   오산시    4326
177   시흥시    9710
193   군포시    6449
209   의왕시    2581
225   하남시    4258
241   용인시   10557
257   이천시    5010
273   안성시    5613
289   김포시    7866
305   화성시    9442
321   광주시    5882
337   여주시    4567
353   양평군    3869
385  의정부시   15633
401  동두천시    5388
417   고양시   23335
433   구리시    6116
449  남양주시   16046
465   파주시   13080
481   양주시    7396
497   포천시    6121
513   연천군    2599
529   가평군    3543

지역별 기초수급자 수 >>

지역별 전체인구 중 기초수급자의 비율을 구해 구급출동 수와 비교