In [1]:
import pandas as pd

In [2]:
data1 = pd.read_csv('data/양적관점df.csv')

In [3]:
data2 = pd.read_csv('data/질적관점df.csv')

In [7]:
data1

,지역,1인/가구당,2인/가구당,3인/가구당,4인/가구당,5인/가구당,6인/가구당,7인 이상/가구당,지역별인구수,독거노인/노인,노인/전체,지역별구급인원,지역별호출건수,지역1인당호출건수,관할인구(명),구급1인당담당인구,구급1인당출동건수
0,가평군,33.271315,32.725287,17.541660,10.948876,3.971849,1.132503,0.408510,63936.0,0.304307,0.232060,226,6489,0.101492,62264,276,28.712389
1,고양시,22.856842,25.887038,24.452592,20.772585,4.746723,1.026187,0.258033,1056853.0,0.230434,0.119979,625,41576,0.039339,1079353,3449,66.521600
2,과천시,18.240711,24.461934,25.784345,24.167470,5.867866,1.054717,0.422957,58325.0,0.194366,0.133288,150,3122,0.053528,73345,489,20.813333
3,광명시,22.068394,26.038126,24.238594,21.611465,4.851989,0.966811,0.224621,333114.0,0.231563,0.120085,218,12627,0.037906,292893,1344,57.922018
4,광주시,22.625609,28.609487,23.278271,18.831774,5.124349,1.156471,0.374040,376819.0,0.215665,0.113946,306,15621,0.041455,387289,1266,51.049020
5,구리시,22.151265,25.447311,24.428862,21.721346,4.929460,1.042101,0.279656,204977.0,0.292775,0.116276,193,9031,0.044059,191948,995,46.792746
6,군포시,21.807390,25.540880,24.452030,22.106191,4.890203,0.924763,0.278543,283876.0,0.231533,0.112070,188,11035,0.038873,268535,1428,58.696809
7,김포시,21.525897,26.202163,23.991663,21.512998,5.284561,1.167030,0.315689,443019.0,0.214535,0.109855,363,17209,0.038845,486508,1340,47.407713
8,남양주시,19.101857,26.573640,24.359206,22.261162,5.940233,1.367916,0.395987,688965.0,0.230657,0.125911,417,26802,0.038902,733798,1760,64.273381
9,동두천시,29.197335,30.129479,19.865148,14.933111,4.445817,1.117499,0.311610,99566.0,0.301567,0.178213,164,6693,0.067222,93592,571,40.810976
10,부천시,24.800557,25.699976,23.752677,20.043736,4.535893,0.923147,0.244013,868106.0,0.232331,0.113001,424,35474,0.040864,806067,1901,83.665094
11,성남시,28.635875,24.970639,22.359611,18.626747,4.243548,0.918118,0.245462,972280.0,0.241298,0.123802,604,42876,0.044098,930948,3093,70.986755
12,수원시,28.750341,22.727525,22.106211,20.676813,4.642218,0.881729,0.215164,1242212.0,0.294084,0.094866,588,51322,0.041315,1183714,4039,87.282313
13,시흥시,26.841491,23.808660,22.166809,20.948115,5.088168,0.897699,0.249058,483327.0,0.291734,0.078169,281,19287,0.039905,512030,1822,68.637011
14,안산시,29.275549,23.733782,21.749437,19.298141,4.753041,0.931914,0.258136,717130.0,0.270976,0.088234,424,32835,0.045787,652726,1539,77.441038
15,안성시,30.725786,28.030324,19.398492,15.659090,4.598304,1.168218,0.419785,194954.0,0.269695,0.150728,273,10879,0.055803,189534,694,39.849817
16,안양시,21.609004,25.370273,24.863892,22.122214,4.847208,0.924462,0.262947,584239.0,0.209415,0.116095,294,22660,0.038785,547178,1861,77.074830
17,양주시,23.565342,28.654656,21.990812,18.636434,5.514064,1.239606,0.399086,224250.0,0.254610,0.139046,304,11045,0.049253,236368,778,36.332237
18,양평군,30.778134,33.224270,17.674947,12.286325,4.309117,1.221955,0.505253,117670.0,0.288913,0.228877,286,7270,0.061783,121230,424,25.419580
19,여주시,28.369180,31.545734,19.146774,14.098322,4.939731,1.335382,0.564878,115074.0,0.269472,0.191008,233,6629,0.057606,112150,481,28.450644
20,연천군,33.854829,31.936536,17.104318,11.100669,4.284372,1.299132,0.420145,45606.0,0.329380,0.232930,232,3792,0.083147,42721,184,16.344828
21,오산시,29.307887,23.067247,20.629216,20.574105,5.168386,0.995579,0.257581,229520.0,0.231300,0.081431,204,9427,0.041073,229983,1127,46.210784
22,용인시,21.170502,24.657904,24.414623,22.798181,5.423817,1.196459,0.338515,1053522.0,0.175363,0.118902,529,35283,0.033491,1077508,2037,66.697543
23,의왕시,20.591632,26.155881,24.782981,22.024142,5.089229,1.061808,0.294326,155084.0,0.196233,0.123585,185,5911,0.038115,163356,883,31.951351
24,의정부시,25.084074,27.017922,22.995153,18.878733,4.721508,1.028345,0.274266,451542.0,0.245071,0.136255,268,23414,0.051853,463661,1730,87.365672
25,이천시,26.367861,27.334310,21.171452,18.162603,5.270262,1.224932,0.468581,221585.0,0.244846,0.126534,280,10416,0.047007,223177,797,37.200000
26,파주시,23.802492,26.867032,22.438939,19.840018,5.442904,1.254846,0.353770,463122.0,0.250651,0.125187,391,20972,0.045284,483245,1236,53.636829
27,평택시,29.816892,25.767119,20.561942,17.810801,4.715329,1.026021,0.301896,518672.0,0.267111,0.113438,549,24628,0.047483,564288,2045,44.859745
28,포천시,30.605238,30.222587,19.342660,13.920634,4.294573,1.194076,0.420233,163474.0,0.308381,0.161310,370,10600,0.064842,148939,403,28.648649
29,하남시,23.879346,26.286615,23.426726,20.151097,5.015702,0.985706,0.254808,256760.0,0.287339,0.118180,208,10092,0.039305,320087,1539,48.519231
30,화성시,26.037625,22.931845,21.910342,22.458313,5.374680,1.020028,0.267168,798100.0,0.217283,0.079821,497,27718,0.034730,887015,1785,55.770624

In [5]:
data2

        신고시각  귀소까지시간  현장과의거리  의식상태 긴급구조구     가중치
0        1.2     1.0     1.2   1.0   수원시  1.4400
1        1.2     1.0     1.0   1.2   수원시  1.4400
2        1.2     1.0     1.0   1.2   수원시  1.4400
3        1.2     1.0     1.2   1.2   안산시  1.7280
4        1.0     1.0     1.0   1.2   군포시  1.2000
...      ...     ...     ...   ...   ...     ...
481521   1.0     1.2     1.0   1.0   안산시  1.2000
481522   1.2     1.0     1.0   1.2   부천시  1.4400
481523   1.2     1.0     1.2   1.0  남양주시  1.4400
481524   1.2     1.2     1.2   1.2   평택시  2.0736
481525   1.2     1.0     1.0   1.2   용인시  1.4400

[481526 rows x 6 columns]

In [10]:
data3 = pd.read_csv('data/소방청_구급활동현황_20181231.csv', encoding='euc-kr')

In [15]:
data3[160000:160005]

,집계년도,시군명,출동소방서,출동안전센터_지역대,신고년월일,신고시각,접수경로,관할구분,출동년월일,출동시각,...,외국인유무,환자증상1,환자증상2,질병외_교통사고,질병외_사고부상,질병외_비외상성손상,의식상태,구급대원1_자격,구급대원2_자격,운전요원_자격
160000,2018,수원시 팔달구,수원남부소방서,지만119안전센터,2018-02-17,17:00,휴대전화,센터외,2018-02-17,17:02,...,N,기타통증,NaN,NaN,기타(사고부상),NaN,A(Alert),응급구조사(1급),NaN,응급구조사(2급)
160001,2018,수원시 영통구,수원소방서,영통119안전센터,2018-02-17,15:18,휴대전화,센터,2018-02-17,15:21,...,N,기타통증,골절,NaN,낙상,NaN,A(Alert),간호사,NaN,응급구조사(2급)
160002,2018,광명시,광명소방서,광남119안전센터,2018-02-18,09:21,휴대전화,센터,2018-02-18,09:23,...,N,복통,NaN,NaN,NaN,NaN,A(Alert),응급구조사(1급),NaN,응급구조사(2급)
160003,2018,시흥시,시흥소방서,시흥119안전센터,2018-02-16,21:32,휴대전화,센터,2018-02-16,21:34,...,N,열상,NaN,NaN,열상,NaN,A(Alert),응급구조사(1급),NaN,응급구조사(1급)
160004,2018,평택시,평택소방서,팽성119안전센터,2018-02-17,07:23,기타,센터,2018-02-17,07:24,...,Y,요통,NaN,NaN,NaN,NaN,A(Alert),간호사,NaN,응급구조사(2급)

In [12]:
data1.head()

,지역,1인/가구당,2인/가구당,3인/가구당,4인/가구당,5인/가구당,6인/가구당,7인 이상/가구당,지역별인구수,독거노인/노인,노인/전체,지역별구급인원,지역별호출건수,지역1인당호출건수,관할인구(명),구급1인당담당인구,구급1인당출동건수
0,가평군,33.271315,32.725287,17.541660,10.948876,3.971849,1.132503,0.408510,63936.0,0.304307,0.232060,226,6489,0.101492,62264,276,28.712389
1,고양시,22.856842,25.887038,24.452592,20.772585,4.746723,1.026187,0.258033,1056853.0,0.230434,0.119979,625,41576,0.039339,1079353,3449,66.521600
2,과천시,18.240711,24.461934,25.784345,24.167470,5.867866,1.054717,0.422957,58325.0,0.194366,0.133288,150,3122,0.053528,73345,489,20.813333
3,광명시,22.068394,26.038126,24.238594,21.611465,4.851989,0.966811,0.224621,333114.0,0.231563,0.120085,218,12627,0.037906,292893,1344,57.922018
4,광주시,22.625609,28.609487,23.278271,18.831774,5.124349,1.156471,0.374040,376819.0,0.215665,0.113946,306,15621,0.041455,387289,1266,51.049020