# 모듈 설치

In [1]:
import os
import sys
# import re
import pickle
from collections import defaultdict, OrderedDict, Counter
import warnings
warnings.filterwarnings('ignore')

# import json
from tqdm import tqdm

In [2]:
import numpy as np
import pandas as pd
# from pandas.plotting import scatter_matrix
# from pandas_profiling import ProfileReport
# from missingno import dendrogram
# import missingno as msno

# pd.options.display.float_format = '{:0.5f}'.format`

In [3]:
# import matplotlib.pyplot as plt
# import seaborn as sns

# settings for seaborn plot sizes
# sns.set(rc={'figure.figsize':(4.5, 3)})

----

# 데이터 수집

## data 파일에 있는 csv 리스트 만들기

In [4]:
import os

dir_path = "data"

path_ls = []
for (root, directories, files) in os.walk(dir_path):
    for file in files:
        file_path = os.path.join(root, file)
        path_ls.append(file_path)

In [5]:
dff_dict= defaultdict(list)
for path in tqdm(path_ls):
    name = path.split('_')[-2]
    dff = pd.read_csv(f'{path}', header=None)
    dff_dict[name].append(dff)

100%|██████████| 68/68 [01:09<00:00,  1.02s/it]

In [ ]:
len(dff_dict)

19

In [ ]:
# 파일 확인
for key, value in dff_dict.items():
    t = '-'
    print(f'{t*20}{key}{t*20}')
    for idx, dff in enumerate(value):
        print(dff)
        print({'-'*20})
    print()
    print()
    print()

--------------------KGUINDTAMOUNT--------------------
                  0   1       2      3         4       5
0        2019-07-17   0     도시락    경기도      의정부시   21000
1        2019-07-17   0  돈까스/일식    경기도      의정부시   35000
2        2019-07-17   0  돈까스/일식   충청북도       제천시   42000
3        2019-07-17   0  배달전문업체    경기도  고양시 일산동구   23125
4        2019-07-17   0  배달전문업체    경기도      의정부시   16633
...             ...  ..     ...    ...       ...     ...
3223127  2021-06-30  23       회    경기도       이천시   34500
3223128  2021-06-30  23       회   경상북도       김천시   53250
3223129  2021-06-30  23       회  부산광역시        남구   20500
3223130  2021-06-30  23       회   전라남도       나주시   12750
3223131  2021-06-30  23       회   충청남도   천안시 동남구  317000

[3223132 rows x 6 columns]
{'--------------------'}



--------------------KGUINDTDLVR--------------------
                  0   1       2      3         4      5
0        2019-07-17   0     도시락    경기도      의정부시  13.52
1        2019-07-17   0  돈까스/일식    경기도      의정부시  13.02
2        2019-07-17   0  돈까스/일식   충청북도       제천시  15.03
3        2019-07-17   0  배달전문업체    경기도  고양시 일산동구  19.49
4        2019-07-17   0  배달전문업체    경기도      의정부시  19.33
...             ...  ..     ...    ...       ...    ...
1940377  2020-09-30  23       회    경기도       화성시  30.40
1940378  2020-09-30  23       회  서울특별시       도봉구  30.97
1940379  2020-09-30  23       회  서울특별시       은평구  20.65
1940380  2020-09-30  23       회   전라북도       군산시  27.45
1940381  2020-09-30  23       회   충청남도       서산시  19.37

[1940382 rows x 6 columns]
{'--------------------'}
                  0   1       2      3         4      5
0        2019-07-17   0     도시락    경기도      의정부시  13.52
1        2019-07-17   0  돈까스/일식    경기도      의정부시  13.02
2        2019-07-17   0  돈까스/일식   충청북도       제천시  15.03
3        2019-07-17   0  배달전문업체    경기도  고양시 일산동구  19.49
4        2019-07-17   0  배달전문업체    경기도      의정부시  19.33
...             ...  ..     ...    ...       ...    ...
3333590  2021-06-30  23       회    경기도       이천시  14.00
3333591  2021-06-30  23       회   경상북도       김천시  26.87
3333592  2021-06-30  23       회  부산광역시        남구  18.88
3333593  2021-06-30  23       회   전라남도       나주시  17.50
3333594  2021-06-30  23       회   충청남도   천안시 동남구  37.63

[3333595 rows x 6 columns]
{'--------------------'}



--------------------KGUINDTORDER--------------------
                  0   1       2      3         4  5
0        2019-07-17   0     도시락    경기도      의정부시  1
1        2019-07-17   0  돈까스/일식    경기도      의정부시  3
2        2019-07-17   0  돈까스/일식   충청북도       제천시  1
3        2019-07-17   0  배달전문업체    경기도  고양시 일산동구  8
4        2019-07-17   0  배달전문업체    경기도      의정부시  3
...             ...  ..     ...    ...       ... ..
1957310  2020-09-30  23       회    경기도       화성시  2
1957311  2020-09-30  23       회  서울특별시       도봉구  1
1957312  2020-09-30  23       회  서울특별시       은평구  7
1957313  2020-09-30  23       회   전라북도       군산시  1
1957314  2020-09-30  23       회   충청남도       서산시  1

[1957315 rows x 6 columns]
{'--------------------'}
                  0   1       2      3         4  5
0        2019-07-17   0     도시락    경기도      의정부시  1
1        2019-07-17   0  돈까스/일식    경기도      의정부시  3
2        2019-07-17   0  돈까스/일식   충청북도       제천시  1
3        2019-07-17   0  배달전문업체    경기도  고양시 일산동구  8
4        2019-07-17   0  배달전문업체    경기도      의정부시  3
...             ...  ..     ...    ...       ... ..
3367311  2021-06-30  23       회    경기도       이천시  3
3367312  2021-06-30  23       회   경상북도       김천시  4
3367313  2021-06-30  23       회  부산광역시        남구  2
3367314  2021-06-30  23       회   전라남도       나주시  2
3367315  2021-06-30  23       회   충청남도   천안시 동남구  1

[3367316 rows x 6 columns]
{'--------------------'}



--------------------KGUPOPLTNINFO--------------------
             0      1        2     3     4     5     6     7
0       201801  11110    서울특별시   종로구  0-4세  4070  2054  2016
1       201802  11110    서울특별시   종로구  0-4세  4049  2049  2000
2       201803  11110    서울특별시   종로구  0-4세  4022  2036  1986
3       201804  11110    서울특별시   종로구  0-4세  4008  2025  1983
4       201805  11110    서울특별시   종로구  0-4세  4007  2017  1990
...        ...    ...      ...   ...   ...   ...   ...   ...
157369  202002  50130  제주특별자치도  서귀포시  100+    99    11    88
157370  202003  50130  제주특별자치도  서귀포시  100+   102    11    91
157371  202004  50130  제주특별자치도  서귀포시  100+   101    10    91
157372  202005  50130  제주특별자치도  서귀포시  100+   101    10    91
157373  202006  50130  제주특별자치도  서귀포시  100+    98    10    88

[157374 rows x 8 columns]
{'--------------------'}
            0      1        2     3     4     5     6     7
0      202007  11110    서울특별시   종로구  0-4세  3315  1678  1637
1      202008  11110    서울특별시   종로구  0-4세  3258  1648  1610
2      202009  11110    서울특별시   종로구  0-4세  3221  1623  1598
3      202010  11110    서울특별시   종로구  0-4세  3171  1596  1575
4      202011  11110    서울특별시   종로구  0-4세  3133  1589  1544
...       ...    ...      ...   ...   ...   ...   ...   ...
62995  202102  50130  제주특별자치도  서귀포시  100+   103    13    90
62996  202103  50130  제주특별자치도  서귀포시  100+    63     4    59
62997  202104  50130  제주특별자치도  서귀포시  100+    66     4    62
62998  202105  50130  제주특별자치도  서귀포시  100+    71     4    67
62999  202106  50130  제주특별자치도  서귀포시  100+    69     4    65

[63000 rows x 8 columns]
{'--------------------'}



--------------------KGURESIDEINFO--------------------
           0      1        2     3       4       5           6   7        8
0       2015  11110    서울특별시   종로구  1세대 가구      부부        일반가구  가구     8162
1       2015  11110    서울특별시   종로구  1세대 가구      부부     주택_단독주택  가구     3409
2       2015  11110    서울특별시   종로구  1세대 가구      부부      주택_아파트  가구     1873
3       2015  11110    서울특별시   종로구  1세대 가구      부부     주택_연립주택  가구      784
4       2015  11110    서울특별시   종로구  1세대 가구      부부    주택_다세대주택  가구     1290
...      ...    ...      ...   ...     ...     ...         ...  ..      ...
412495  2019  50130  제주특별자치도  서귀포시  비친족 가구  비친족 가구     가구원수 4명  가구       53
412496  2019  50130  제주특별자치도  서귀포시  비친족 가구  비친족 가구     가구원수 5명  가구       23
412497  2019  50130  제주특별자치도  서귀포시  비친족 가구  비친족 가구     가구원수 6명  가구  다섯가구 미만
412498  2019  50130  제주특별자치도  서귀포시  비친족 가구  비친족 가구  가구원수 7명 이상  가구  다섯가구 미만
412499  2019  50130  제주특별자치도  서귀포시  비친족 가구  비친족 가구     평균 가구원수   명      2.2

[412500 rows x 9 columns]
{'--------------------'}
          0      1        2     3       4       5           6   7        8
0      2020  11110    서울특별시   종로구  1세대 가구      부부        일반가구  가구     8752
1      2020  11110    서울특별시   종로구  1세대 가구      부부     주택_단독주택  가구     3162
2      2020  11110    서울특별시   종로구  1세대 가구      부부      주택_아파트  가구     2628
3      2020  11110    서울특별시   종로구  1세대 가구      부부     주택_연립주택  가구      836
4      2020  11110    서울특별시   종로구  1세대 가구      부부    주택_다세대주택  가구     1406
...     ...    ...      ...   ...     ...     ...         ...  ..      ...
82495  2020  50130  제주특별자치도  서귀포시  비친족 가구  비친족 가구     가구원수 4명  가구       43
82496  2020  50130  제주특별자치도  서귀포시  비친족 가구  비친족 가구     가구원수 5명  가구       21
82497  2020  50130  제주특별자치도  서귀포시  비친족 가구  비친족 가구     가구원수 6명  가구  다섯가구 미만
82498  2020  50130  제주특별자치도  서귀포시  비친족 가구  비친족 가구  가구원수 7명 이상  가구  다섯가구 미만
82499  2020  50130  제주특별자치도  서귀포시  비친족 가구  비친족 가구     평균 가구원수   명      2.2

[82500 rows x 9 columns]
{'--------------------'}



--------------------KGUTIMEAMOUNT--------------------
                  0   1     2         3     4      5
0        2019-07-17   0   강원도       속초시    교동  21000
1        2019-07-17   0   경기도  고양시 일산동구  정발산동  23125
2        2019-07-17   0   경기도      의정부시   가능동  20929
3        2019-07-17   0   경기도      의정부시   금오동  30500
4        2019-07-17   0   경기도      의정부시   낙양동  25000
...             ...  ..   ...       ...   ...    ...
1284912  2020-09-30  23  충청남도       서산시   예천동  25333
1284913  2020-09-30  23  충청남도       서산시   읍내동  23750
1284914  2020-09-30  23  충청북도       제천시   강제동  24900
1284915  2020-09-30  23  충청북도       제천시   신백동  23100
1284916  2020-09-30  23  충청북도       제천시   청전동  14500

[1284917 rows x 6 columns]
{'--------------------'}
                  0   1     2         3     4      5
0        2019-07-17   0   강원도       속초시    교동  21000
1        2019-07-17   0   경기도  고양시 일산동구  정발산동  23125
2        2019-07-17   0   경기도      의정부시   가능동  20929
3        2019-07-17   0   경기도      의정부시   금오동  30500
4        2019-07-17   0   경기도      의정부시   낙양동  25000
...             ...  ..   ...       ...   ...    ...
2165127  2021-06-30  23  충청북도       제천시   신백동  20250
2165128  2021-06-30  23  충청북도       제천시   영천동  12000
2165129  2021-06-30  23  충청북도       제천시   천남동  20275
2165130  2021-06-30  23  충청북도       제천시   청전동  19700
2165131  2021-06-30  23  충청북도       제천시   하소동  18500

[2165132 rows x 6 columns]
{'--------------------'}



--------------------KGUTIMEDLVR--------------------
                  0   1     2         3     4      5
0        2019-07-17   0   경기도  고양시 일산동구  정발산동  19.49
1        2019-07-17   0   경기도      의정부시   가능동  15.77
2        2019-07-17   0   경기도      의정부시   금오동  19.27
3        2019-07-17   0   경기도      의정부시   낙양동  19.32
4        2019-07-17   0   경기도      의정부시   민락동  30.12
...             ...  ..   ...       ...   ...    ...
1318805  2020-09-30  23  충청남도       서산시   예천동  15.35
1318806  2020-09-30  23  충청남도       서산시   읍내동  11.20
1318807  2020-09-30  23  충청북도       제천시   강제동  24.62
1318808  2020-09-30  23  충청북도       제천시   신백동  32.07
1318809  2020-09-30  23  충청북도       제천시   청전동  23.90

[1318810 rows x 6 columns]
{'--------------------'}
                  0   1     2         3     4      5
0        2019-07-17   0   경기도  고양시 일산동구  정발산동  19.49
1        2019-07-17   0   경기도      의정부시   가능동  15.77
2        2019-07-17   0   경기도      의정부시   금오동  19.27
3        2019-07-17   0   경기도      의정부시   낙양동  19.32
4        2019-07-17   0   경기도      의정부시   민락동  30.12
...             ...  ..   ...       ...   ...    ...
2206460  2021-06-30  23  충청북도       제천시   신백동  25.82
2206461  2021-06-30  23  충청북도       제천시   영천동  16.53
2206462  2021-06-30  23  충청북도       제천시   천남동  27.54
2206463  2021-06-30  23  충청북도       제천시   청전동  29.86
2206464  2021-06-30  23  충청북도       제천시   하소동  27.61

[2206465 rows x 6 columns]
{'--------------------'}



--------------------KGUTIMEORDER--------------------
                  0   1     2         3     4   5
0        2019-07-17   0   강원도       속초시    교동   1
1        2019-07-17   0   경기도  고양시 일산동구  정발산동   8
2        2019-07-17   0   경기도      의정부시   가능동   7
3        2019-07-17   0   경기도      의정부시   금오동   5
4        2019-07-17   0   경기도      의정부시   낙양동   1
...             ...  ..   ...       ...   ...  ..
1338222  2020-09-30  23  충청남도       서산시   예천동  14
1338223  2020-09-30  23  충청남도       서산시   읍내동   4
1338224  2020-09-30  23  충청북도       제천시   강제동   1
1338225  2020-09-30  23  충청북도       제천시   신백동   2
1338226  2020-09-30  23  충청북도       제천시   청전동   1

[1338227 rows x 6 columns]
{'--------------------'}
                  0   1     2         3     4  5
0        2019-07-17   0   강원도       속초시    교동  1
1        2019-07-17   0   경기도  고양시 일산동구  정발산동  8
2        2019-07-17   0   경기도      의정부시   가능동  7
3        2019-07-17   0   경기도      의정부시   금오동  5
4        2019-07-17   0   경기도      의정부시   낙양동  1
...             ...  ..   ...       ...   ... ..
2240802  2021-06-30  23  충청북도       제천시   신백동  2
2240803  2021-06-30  23  충청북도       제천시   영천동  1
2240804  2021-06-30  23  충청북도       제천시   천남동  4
2240805  2021-06-30  23  충청북도       제천시   청전동  5
2240806  2021-06-30  23  충청북도       제천시   하소동  2

[2240807 rows x 6 columns]
{'--------------------'}



--------------------KGUTRDARINFO--------------------
          0     1   2    3      4         5             6        7       8  \
0      2019   강원도  42  강릉시  42150  관광/여가/오락  PC/오락/당구/볼링등       기원  N01A09
1      2019   강원도  42  강릉시  42150  관광/여가/오락  PC/오락/당구/볼링등      당구장  N01A03
2      2019   강원도  42  강릉시  42150  관광/여가/오락  PC/오락/당구/볼링등      볼링장  N01A06
3      2019   강원도  42  강릉시  42150  관광/여가/오락  PC/오락/당구/볼링등   비디오감상실  N01A02
4      2019   강원도  42  강릉시  42150  관광/여가/오락  PC/오락/당구/볼링등   인터넷PC방  N01A01
...     ...   ...  ..  ...    ...       ...           ...      ...     ...
93312  2019  충청북도  43  충주시  43130     학문/교육          학원기타   운전연수전문  R09A03
93313  2019  충청북도  43  충주시  43130     학문/교육          학원기타   학원(종합)  R09A01
93314  2019  충청북도  43  충주시  43130     학문/교육          학원기타    학원-기타  R09A11
93315  2019  충청북도  43  충주시  43130     학문/교육          학원기타   학원-말더듬  R09A09
93316  2019  충청북도  43  충주시  43130     학문/교육          학원기타  학원-심리변론  R09A07

         9
0        8
1       70
2        4
3        8
4      126
...    ...
93312    1
93313  166
93314   33
93315    1
93316    1

[93317 rows x 10 columns]
{'--------------------'}
          0     1   2    3      4         5             6       7       8    9
0      2020   강원도  42  강릉시  42150  관광/여가/오락  PC/오락/당구/볼링등      기원  N01A09    6
1      2020   강원도  42  강릉시  42150  관광/여가/오락  PC/오락/당구/볼링등     당구장  N01A03   56
2      2020   강원도  42  강릉시  42150  관광/여가/오락  PC/오락/당구/볼링등     볼링장  N01A06    5
3      2020   강원도  42  강릉시  42150  관광/여가/오락  PC/오락/당구/볼링등  비디오감상실  N01A02    7
4      2020   강원도  42  강릉시  42150  관광/여가/오락  PC/오락/당구/볼링등  인터넷PC방  N01A01  109
...     ...   ...  ..  ...    ...       ...           ...     ...     ...  ...
66329  2020  충청북도  43  충주시  43130     학문/교육     학원-창업취업취미  학원-목공예  R02A14    1
66330  2020  충청북도  43  충주시  43130     학문/교육        학원-컴퓨터   컴퓨터학원  R06A01   13
66331  2020  충청북도  43  충주시  43130     학문/교육          학원기타  운전연수전문  R09A03    1
66332  2020  충청북도  43  충주시  43130     학문/교육          학원기타  학원(종합)  R09A01  136
66333  2020  충청북도  43  충주시  43130     학문/교육          학원기타   학원-기타  R09A11   46

[66334 rows x 10 columns]
{'--------------------'}



--------------------KGUWETHERINFO--------------------
              0      1     2        3         4     5   6   7    8     9   \
0              1  42150   강원도      강릉시  20190101     0  없음  25    0  -0.3
1              2  42820   강원도      고성군  20190101     0  없음  23    0   0.6
2              3  42170   강원도      동해시  20190101     0  없음  25    0   2.1
3              4  42230   강원도      삼척시  20190101     0  없음  23    0   1.3
4              5  42210   강원도      속초시  20190101     0  없음  20    0   1.2
...          ...    ...   ...      ...       ...   ...  ..  ..  ...   ...
4019995  4019996  43111  충청북도  청주시 상당구  20201031  2300   비  99  0.5   9.9
4019996  4019997  43112  충청북도  청주시 서원구  20201031  2300   비  99  0.5   9.9
4019997  4019998  43114  충청북도  청주시 청원구  20201031  2300   비  99  0.5   9.9
4019998  4019999  43113  충청북도  청주시 흥덕구  20201031  2300   비  81  0.5  12.1
4019999  4020000  43130  충청북도      충주시  20201031  2300  없음  82    0  11.4

          10   11    12   13   14
0        4.5  약간강  east  228   SW
1        1.9    약  east  271    W
2        1.8    약  east  231   SW
3          2    약  east  222   SW
4        0.1    약  east    7    N
...      ...  ...   ...  ...  ...
4019995    0    약  none  281    W
4019996    0    약  none  281    W
4019997    0    약  none  281    W
4019998    0    약  none  237  WSW
4019999  1.9    약  east  279    W

[4020000 rows x 15 columns]
{'--------------------'}
              0      1        2     3         4     5   6   7    8     9   \
0        4020001  11110    서울특별시   종로구  20201109     0  없음  49  0.0   2.5
1        4020002  11140    서울특별시    중구  20201109     0  없음  49  0.0   2.5
2        4020003  11170    서울특별시   용산구  20201109     0  없음  48  0.0   4.8
3        4020004  11200    서울특별시   성동구  20201109     0  없음  33  0.0   4.7
4        4020005  11230    서울특별시  동대문구  20201109     0  없음  33  0.0   4.7
...          ...    ...      ...   ...       ...   ...  ..  ..  ...   ...
1606745  5626746  48870     경상남도   함양군  20210831  2000  없음  91  0.0  24.6
1606746  5626747  48880     경상남도   거창군  20210831  2000  없음  89  0.0  23.6
1606747  5626748  48890     경상남도   합천군  20210831  2000  없음  95  0.0  25.1
1606748  5626749  50110  제주특별자치도   제주시  20210831  2000  없음  79  0.0  27.7
1606749  5626750  50130  제주특별자치도  서귀포시  20210831  2000  없음  87  0.0  26.2

          10 11    12   13   14
0        0.8  약  east  350    N
1        0.8  약  east  350    N
2        0.9  약  none  358    N
3        0.5  약  east  283  WNW
4        0.5  약  east  283  WNW
...      ... ..   ...  ...  ...
1606745  0.2  약  west   94    E
1606746  1.3  약  east  356    N
1606747  0.0  약  none    0    N
1606748  0.7  약  west  102  ESE
1606749  1.1  약  east  237  WSW

[1606750 rows x 15 columns]
{'--------------------'}



--------------------KGUAREAAVDSTN--------------------
        0  1       2     3        4    5        6
0    2019  5      한식   경기도  수원시 장안구   14  2637.64
1    2019  5   패스트푸드   경기도  수원시 팔달구    6  2188.17
2    2019  5  카페/디저트   경기도      양주시    1   838.00
3    2019  5      분식   경기도     의정부시  168  1274.61
4    2019  5   족발/보쌈   경기도     의정부시   12  1048.58
..    ... ..     ...   ...      ...  ...      ...
180  2019  6   패스트푸드  충청북도      제천시  962   892.69
181  2019  6      피자  충청북도      제천시   18  1952.78
182  2019  6      한식  충청북도      제천시  601  1490.68
183  2019  6       회  충청북도      제천시   83  1713.43
184  2019  6      분식  충청북도  청주시 상당구    1   534.00

[185 rows x 7 columns]
{'--------------------'}
         0   1       2     3        4     5        6
0     2019   7  카페/디저트   강원도      삼척시     2  1649.00
1     2019   7  돈까스/일식   강원도      속초시   263  1537.25
2     2019   7      분식   강원도      속초시  1632  1663.40
3     2019   7  아시안/양식   강원도      속초시   213  1289.70
4     2019   7   족발/보쌈   강원도      속초시    45  1782.69
...    ...  ..     ...   ...      ...   ...      ...
3298  2019  12       회  충청북도      제천시  1049  1967.76
3299  2019  12      치킨  충청북도  청주시 청원구    90   807.53
3300  2019  12  카페/디저트  충청북도  청주시 청원구   681   831.49
3301  2019  12      한식  충청북도  청주시 청원구    49   994.94
3302  2019  12  카페/디저트  충청북도  청주시 흥덕구    41   571.93

[3303 rows x 7 columns]
{'--------------------'}
         0  1       2     3        4     5        6
0     2020  1  카페/디저트   강원도      강릉시   188  1411.56
1     2020  1  카페/디저트   강원도      삼척시    82  1036.74
2     2020  1  카페/디저트   강원도      원주시  1737  1075.13
3     2020  1     도시락   경기도  고양시 덕양구   835  1563.44
4     2020  1  돈까스/일식   경기도  고양시 덕양구  2156  1330.03
...    ... ..     ...   ...      ...   ...      ...
3616  2020  6      한식  충청북도      제천시  5147  1609.63
3617  2020  6       회  충청북도      제천시   452  1821.52
3618  2020  6  카페/디저트  충청북도  청주시 청원구   952   827.31
3619  2020  6      치킨  충청북도      충주시    58  1155.81
3620  2020  6  카페/디저트  충청북도      충주시     4  1975.00

[3621 rows x 7 columns]
{'--------------------'}
         0   1       2     3        4     5        6
0     2020   7  카페/디저트   강원도      강릉시   162  1347.98
1     2020   7  카페/디저트   강원도      삼척시    94   993.16
2     2020   7  카페/디저트   강원도      원주시  2388  1106.00
3     2020   7  돈까스/일식   경기도  고양시 덕양구  2871  1323.14
4     2020   7  배달전문업체   경기도  고양시 덕양구   178  1602.99
...    ...  ..     ...   ...      ...   ...      ...
3550  2020  12  카페/디저트  충청북도      제천시   821  1598.97
3551  2020  12   패스트푸드  충청북도      제천시   520  1508.84
3552  2020  12      한식  충청북도      제천시  4586  1695.79
3553  2020  12       회  충청북도      제천시   696  1905.54
3554  2020  12  카페/디저트  충청북도  청주시 청원구  2518   713.09

[3555 rows x 7 columns]
{'--------------------'}
         0  1       2        3        4     5        6
0     2021  1  카페/디저트      강원도      강릉시    63  1410.48
1     2021  1  카페/디저트      강원도      삼척시   159  1092.42
2     2021  1  카페/디저트      강원도      원주시  5334  1071.45
3     2021  1  돈까스/일식      경기도  고양시 덕양구  3227  1369.70
4     2021  1  배달전문업체      경기도  고양시 덕양구   226  1658.73
...    ... ..     ...      ...      ...   ...      ...
3441  2021  6       회     전라북도      정읍시    96  1892.10
3442  2021  6       회  제주특별자치도     서귀포시    44  1501.68
3443  2021  6       회     충청남도  천안시 동남구   232  1575.12
3444  2021  6       회     충청남도  천안시 서북구    25   998.00
3445  2021  6       회     충청북도      제천시   190  1717.04

[3446 rows x 7 columns]
{'--------------------'}
        0  1    2        3        4     5        6
0    2021  7  도시락      경기도      광주시    21   890.05

- KGUINDTAMOUNT
    - 이상무
- KGUINDTDLVR
    - [-1]
- KGUINDTORDER
    - [-1]
- KGUPOPLTNINFO
    - 연결
- KGURESIDEINFO
    - 연결
- KGUTIMEAMOUNT
    - [-1]
- KGUTIMEDLVR
    - [-1]
- KGUTIMEORDER
    - [-1]
- KGUTRDARINFO
    - 연결
- KGUWETHERINFO
    - 연결
    - 앞의 끝은 20201031
    - 뒤의 시작은 20201109
    - 공백 존재
- KGUAREAAVDSTN
    - 연결
- KGUAREADOITEM
    - 연결
    - 날짜에 이상한 에러가 보임
        - ﻿2021-07-01
        - 확인 필요
- KGUAREAINDPAY
    - 연결
- KGUDSTNAMOUNT
    - 연결
- KGUDSTNORDER
    - 연결
- KGUINSCTNINFO
    - 특별취급 / 연결
    - 데이터 중에 칼럼 있는거 하고 없는게 있음
    - 결합후 데이터 확인 필요
        - ﻿2021
        - ﻿YEAR
- KGUINSCTNORDR
    - 연결
- KGUWTHRDLVRDF
    - 연결
- KGUDLIVERYSTORE00001
    - 배달 상점 데이터
    - 흠...
    - 결합하고 배달상점ID(cols[0]) 기준으로 duplicate 하고 최신 버전으로 간주되는 마지막꺼를 살리기

- [-1]
    - 버전이 올라갈수록 기존 버전을 포함하며 업데이트되는 형식
    - 마지막 버전만 최종데이터로 판단하기
    - 5개
    - ['KGUINDTDLVR', 'KGUINDTORDER', 'KGUTIMEAMOUNT', 'KGUTIMEDLVR', 'KGUTIMEORDER']
- 이상무
    - 버전이 하나만 존재
    - 1개
    - ['KGUINDTAMOUNT']
- 연결
    - 버전이 올라갈수록 기존 버전의 다음 내용들을 업데이트하는 형식
    - 데이터 결합
    - 11개
    - ['KGUPOPLTNINFO', 'KGURESIDEINFO', 'KGUTRDARINFO', 'KGUWETHERINFO', 'KGUAREAAVDSTN', 'KGUAREADOITEM', 'KGUAREAINDPAY', 'KGUDSTNAMOUNT', 'KGUDSTNORDER', 'KGUINSCTNORDR', 'KGUWTHRDLVRDF']
- 특별취급
    - 2개
    - KGUDLIVERYSTORE00001, KGUINSCTNINFO

## 같은 유형의 파일끼리 연결

In [23]:
concat_dff_dict = defaultdict()
for key, value in dff_dict.items():
    print(f'----------{key}----------')
    
    # 버전이 올라갈수록 기존 버전을 포함하며 업데이트되는 형식
    keys = ['KGUINDTDLVR', 'KGUINDTORDER', 'KGUTIMEAMOUNT', 'KGUTIMEDLVR', 'KGUTIMEORDER']
    if key in keys:
        dff = value[-1]
    
    # 버전이 올라갈수록 기존 버전의 다음 내용들을 업데이트하는 형식
    keys = ['KGUPOPLTNINFO', 'KGURESIDEINFO', 'KGUTRDARINFO', 'KGUWETHERINFO', \
        'KGUAREAAVDSTN', 'KGUAREADOITEM', 'KGUAREAINDPAY', 'KGUDSTNAMOUNT', \
            'KGUDSTNORDER', 'KGUINSCTNORDR', 'KGUWTHRDLVRDF']
    if key in keys:
        dff = pd.concat(value)
    
    # 버전이 하나만 존재
    keys = ['KGUINDTAMOUNT']
    if key in keys:
        dff = value[0]  

    # 특별 취급
    keys = ['KGUDLIVERYSTORE00001', 'KGUINSCTNINFO']
    if key in keys:
        # 칼럼이 존재하는 버전이 있고 없는 버전이 있음
        # 시점은 다 다른 버전이므로 칼럼 유무에 다르게 결합
        if key == 'KGUINSCTNINFO':
            df_ls = []
            for df in value:
                # print(str(df.iloc[0,0])[-1])
                try:        # 첫행 1열이 int 가능 하면 칼럼x
                    # print('try')
                    check = int(str(df.iloc[0,0])[-1])
                    df_ls.append(df)
                except:     # 첫행 1열이 int 불가능 하면 칼럼o
                    # print('except', str(df.iloc[0,0])[-1])
                    df_ls.append(df.drop(0, axis=0))
            dff = pd.concat(df_ls)
        # 연결후 배달 상점ID가 같은 중복 데이터가 있으면 마지막꺼 살리기
        if key == 'KGUDLIVERYSTORE00001':
            dff = pd.concat(dff_dict[key])
            dff.drop_duplicates(subset=list(dff.columns)[0], keep='last', inplace=True)
        
    concat_dff_dict[key] = (dff)

----------KGUINDTAMOUNT----------
----------KGUINDTDLVR----------
----------KGUINDTORDER----------
----------KGUPOPLTNINFO----------
----------KGURESIDEINFO----------
----------KGUTIMEAMOUNT----------
----------KGUTIMEDLVR----------
----------KGUTIMEORDER----------
----------KGUTRDARINFO----------
----------KGUWETHERINFO----------
----------KGUAREAAVDSTN----------
----------KGUAREADOITEM----------
----------KGUAREAINDPAY----------
----------KGUDSTNAMOUNT----------
----------KGUDSTNORDER----------
----------KGUINSCTNINFO----------
9
9
0
0
R
1
----------KGUINSCTNORDR----------
----------KGUWTHRDLVRDF----------
----------KGUDLIVERYSTORE00001----------

In [24]:
for code, dff in concat_dff_dict.items():
    print(f'{code} - {dff.shape}')

KGUINDTAMOUNT - (3223132, 6)
KGUINDTDLVR - (3333595, 6)
KGUINDTORDER - (3367316, 6)
KGUPOPLTNINFO - (220374, 8)
KGURESIDEINFO - (495000, 9)
KGUTIMEAMOUNT - (2165132, 6)
KGUTIMEDLVR - (2206465, 6)
KGUTIMEORDER - (2240807, 6)
KGUTRDARINFO - (159651, 10)
KGUWETHERINFO - (5626750, 15)
KGUAREAAVDSTN - (14606, 7)
KGUAREADOITEM - (26398236, 6)
KGUAREAINDPAY - (11023306, 6)
KGUDSTNAMOUNT - (3794787, 6)
KGUDSTNORDER - (3794787, 6)
KGUINSCTNINFO - (30103, 23)
KGUINSCTNORDR - (54754, 7)
KGUWTHRDLVRDF - (380741, 27)
KGUDLIVERYSTORE00001 - (83159, 11)

----

## 칼럼명 추가

In [25]:
all_dict = defaultdict(list)

In [26]:
text = '날씨별 배달 품목차이'
code = 'KGUWTHRDLVRDF'
ls = ['광역시도명',
'시군구명',
'날짜',
'시간대별 시간',
'강수 유형명',
'습도값',
'강수량 값',
'기온값',
'풍속값',
'바람강도 유형명',
'동쪽서쪽바람유형명',
'풍향값',
'풍향카테고리명',
'한식_배달건수',
'분식_배달건수',
'카페/디저트_배달건수',
'돈까스/일식_배달건수',
'회_배달건수',
'치킨_배달건수',
'피자_배달건수',
'아시안/양식_배달건수',
'중식_배달건수',
'족발/보쌈_배달건수',
'야식_배달건수',
'찜탕_배달건수',
'도시락_배달건수',
'패스트푸드_배달건수']
all_dict[text].append(code)
all_dict[text].append(ls)

In [27]:
text = '지역-업종 배달평균거리'
code = 'KGUAREAAVDSTN'
ls = ['년도',
'월',
'배달상점 업종명',
'배달상점 광역시도명',
'배달상점 시군구명',
'배달주문수',
'배달평균거리값']
all_dict[text].append(code)
all_dict[text].append(ls)

In [28]:
text = '배달 상점 데이터'
code = 'KGUDLIVERYSTORE00001'
ls = ['배달상점ID'	,
'배달상점 업종명',
'배달상점 법정동코드'	,
'배달상점 시도명'	,
'배달상점 시군구명'	,
'배달상점 법정동 읍면동명'	,
'배달상점 법정동 리명'	,
'배달상점 행정동코드',
'배달상점 행정동 읍면동명'	,
'배달상점 도로명주소코드',
'배달상점 도로명주소 도로명']
all_dict[text].append(code)
all_dict[text].append(ls)

In [29]:
text = '업종 목적지별 배달 주문건수'
code = 'KGUDSTNORDER'
ls = ['날짜',
'시간대별 시간',
'배달상점 업종명',
'목적지 광역시도명',
'목적지 시군구명',
'주문 건수']
all_dict[text].append(code)
all_dict[text].append(ls)

In [30]:
text = '업종-거리구간 배달 건수'
code = 'KGUINSCTNORDR'
ls = ['년도',
'월',
'배달상점 업종명',
'배달상점 광역시도명',
'배달상점 시군구명',
'배달거리 구간명',
'배달주문수']
all_dict[text].append(code)
all_dict[text].append(ls)

In [31]:
text = '업종 목적지별 평균주문금액'
code = 'KGUDSTNAMOUNT'
ls = ['날짜',
'시간대별 시간',
'배달상점 업종명',
'목적지 광역시도명',
'목적지 시군구명',
'평균주문금액']
all_dict[text].append(code)
all_dict[text].append(ls)

In [32]:
text = '주문지역 주거 특성'
code = 'KGURESIDEINFO'
ls = ['기준연도',	'시군구코드',	'시도명',	'시군구명',	'세대구성대분류',	'세대구성중분류',	'세대구성소분류',	'단위','빈도수']
all_dict[text].append(code)
all_dict[text].append(ls)

In [33]:
text = '주문지역 상권유형 특성'
code = 'KGUTRDARINFO'
ls = ['기준연도',	'시도명',	'시도코드',	'시군구명'	,'시군구코드'	,'상권업종대분류명',	'상권업종중분류명'	,'상권업종소분류명'	,'상권업종소분류코드'	,'상권업종개수']
all_dict[text].append(code)
all_dict[text].append(ls)

In [34]:
text = '주문지역 인구 특성'
code = 'KGUPOPLTNINFO'
ls = ['기준연월',	'시군구코드',	'시도명',	'시군구명'	,'5세단위구분'	,'총인구수'	,'남성인구수','여성인구수']
all_dict[text].append(code)
all_dict[text].append(ls)

In [35]:
text = '주문지역 기상 정보'
code = 'KGUWETHERINFO'
ls = ['순번',	'시군구코드',	'광역시도명',	'시군구명',	'공개 일',	'공개 시간',\
    '강수 유형명',	'습도',	'1시간 강수량 값',	'기온',	'풍속',	\
    '바람강도 유형명',	'동쪽서쪽바람유형명',	'풍향값',	'풍향카테고리명']
all_dict[text].append(code)
all_dict[text].append(ls)

In [36]:
text = '지역-업종 결제정보'
code = 'KGUAREAINDPAY'
ls = ['날짜',
'24시기준 해당시간',
'배달상점 업종명',
'배달상점 광역시도명',
'배달상점 시군구명',
'결제종류값']
all_dict[text].append(code)
all_dict[text].append(ls)

In [37]:
text = '지역-요일 배달 품목정보'
code = 'KGUAREADOITEM'
ls = ['날짜',
'24시기준 해당시간',
'주문요일명',
'배달상점 광역시도명',
'배달상점 시군구명',
'배달상점 업종명']
all_dict[text].append(code)
all_dict[text].append(ls)

In [38]:
text = '업종-거리구간 상권 정보'
code = 'KGUINSCTNINFO'
ls = ['년도',
'월',
'배달상점 업종명',
'배달상점 광역시도명',
'배달상점 시군구명',
'1km이하 배달건수',
'1km초과3km이하배달건수',
'3km초과5km이하배달건수',
'거리 5000이상',
'한식_매장수',
'분식_매장수',
'카페/디저트_매장수',
'돈까스/일식_매장수',
'회_매장수',
'치킨_매장수',
'피자_매장수',
'아시안/양식_매장수',
'중식_매장수',
'족발/보쌈_매장수',
'야식_매장수',
'찜탕_매장수',
'도시락_매장수',
'패스트푸드_매장수']
all_dict[text].append(code)
all_dict[text].append(ls)

In [39]:
text = '시간-지역별 배달 주문건수'
code = 'KGUTIMEORDER'
ls = ['날짜',	'시간대별 시간',	'배달상점 광역시도명',	'배달상점 시군구명',	'배달상점 법정동명',	'주문건수']
all_dict[text].append(code) 
all_dict[text].append(ls)

In [40]:
text = '시간-지역별 배달 평균주문금액'
code = 'KGUTIMEAMOUNT'
ls = ['날짜',	'시간대별 시간',	'배달상점 광역시도명',	\
    '배달상점 시군구명',	'배달상점 법정동명',	'평균주문금액']
all_dict[text].append(code) 
all_dict[text].append(ls)

In [41]:
text = '시간-지역별 배달 소요시간평균'
code = 'KGUTIMEDLVR'
ls = ['날짜',	'시간대별 시간',	'배달상점 업종명',\
    '배달상점 광역시도명',    '배달상점 시군구명',	'평균배달소요시간']
all_dict[text].append(code) 
all_dict[text].append(ls)

In [42]:
text = '업종-지역별 평균주문금액'
code = 'KGUINDTAMOUNT'
ls = ['날짜',	'시간대별 시간',	'배달상점 업종명',	'배달상점 광역시도명',	'배달상점 시군구명',	'평균주문금액']
all_dict[text].append(code)
all_dict[text].append(ls)

In [43]:
text = '업종-지역별 배달 주문건수'
code = 'KGUINDTORDER'
ls = ['날짜',	'시간대별 시간',	'배달상점 업종명',	'배달상점 광역시도명',	'배달상점 시군구명',	'주문 건수']
all_dict[text].append(code) 
all_dict[text].append(ls)

In [44]:
text = '업종-지역별 평균배달소요시간'
code = 'KGUINDTDLVR'
ls = ['날짜',	'시간대별 시간',	'배달상점 업종명',	'배달상점 광역시도명',	'배달상점 시군구명',	'평균배달소요시간(분)']
all_dict[text].append(code) 
all_dict[text].append(ls)

In [45]:
concat_dff_codes = set(concat_dff_dict.keys())
check_codes = set()
for name, ls in all_dict.items():
    # print(name)
    code = ls[0]
    if code in concat_dff_codes:
        check_codes.add(code)
print(concat_dff_codes - check_codes)

set()

- 모든 데이터에 대한 칼럼명 리스트 생성 확인

In [46]:
for name, ls in all_dict.items():
    # print(name)
    code = ls[0]
    cols = ls[1]
    try:
        # print('성공')
        concat_dff_dict[code].columns = cols
    except:
        print(name)
        print(cols)
        print(concat_dff_dict[code].columns)
        print()
    # cols = ls[1]
    # concat_dff_dict[code].columns = cols

In [47]:
for code, dff in concat_dff_dict.items():
    print(code)
    print(dff.shape)
    print(dff.columns)
    print()

KGUINDTAMOUNT
(3223132, 6)
Index(['날짜', '시간대별 시간', '배달상점 업종명', '배달상점 광역시도명', '배달상점 시군구명', '평균주문금액'], dtype='object')

KGUINDTDLVR
(3333595, 6)
Index(['날짜', '시간대별 시간', '배달상점 업종명', '배달상점 광역시도명', '배달상점 시군구명', '평균배달소요시간(분)'], dtype='object')

KGUINDTORDER
(3367316, 6)
Index(['날짜', '시간대별 시간', '배달상점 업종명', '배달상점 광역시도명', '배달상점 시군구명', '주문 건수'], dtype='object')

KGUPOPLTNINFO
(220374, 8)
Index(['기준연월', '시군구코드', '시도명', '시군구명', '5세단위구분', '총인구수', '남성인구수', '여성인구수'], dtype='object')

KGURESIDEINFO
(495000, 9)
Index(['기준연도', '시군구코드', '시도명', '시군구명', '세대구성대분류', '세대구성중분류', '세대구성소분류', '단위',
       '빈도수'],
      dtype='object')

KGUTIMEAMOUNT
(2165132, 6)
Index(['날짜', '시간대별 시간', '배달상점 광역시도명', '배달상점 시군구명', '배달상점 법정동명', '평균주문금액'], dtype='object')

KGUTIMEDLVR
(2206465, 6)
Index(['날짜', '시간대별 시간', '배달상점 업종명', '배달상점 광역시도명', '배달상점 시군구명', '평균배달소요시간'], dtype='object')

KGUTIMEORDER
(2240807, 6)
Index(['날짜', '시간대별 시간', '배달상점 광역시도명', '배달상점 시군구명', '배달상점 법정동명', '주문건수'], dtype='object')

KGUTRDARINFO
(159651, 10)
Index(['기준연도', '시도명', '시도코드', '시군구명', '시군구코드', '상권업종대분류명', '상권업종중분류명',
       '상권업종소분류명', '상권업종소분류코드', '상권업종개수'],
      dtype='object')

KGUWETHERINFO
(5626750, 15)
Index(['순번', '시군구코드', '광역시도명', '시군구명', '공개 일', '공개 시간', '강수 유형명', '습도',
       '1시간 강수량 값', '기온', '풍속', '바람강도 유형명', '동쪽서쪽바람유형명', '풍향값', '풍향카테고리명'],
      dtype='object')

KGUAREAAVDSTN
(14606, 7)
Index(['년도', '월', '배달상점 업종명', '배달상점 광역시도명', '배달상점 시군구명', '배달주문수', '배달평균거리값'], dtype='object')

KGUAREADOITEM
(26398236, 6)
Index(['날짜', '24시기준 해당시간', '주문요일명', '배달상점 광역시도명', '배달상점 시군구명', '배달상점 업종명'], dtype='object')

KGUAREAINDPAY
(11023306, 6)
Index(['날짜', '24시기준 해당시간', '배달상점 업종명', '배달상점 광역시도명', '배달상점 시군구명', '결제종류값'], dtype='object')

KGUDSTNAMOUNT
(3794787, 6)
Index(['날짜', '시간대별 시간', '배달상점 업종명', '목적지 광역시도명', '목적지 시군구명', '평균주문금액'], dtype='object')

KGUDSTNORDER
(3794787, 6)
Index(['날짜', '시간대별 시간', '배달상점 업종명', '목적지 광역시도명', '목적지 시군구명', '주문 건수'], dtype='object')

KGUINSCTNINFO
(30103, 23)
Index(['년도', '월', '배달상점 업종명', '배달상점 광역시도명', '배달상점 시군구명', '1km이하 배달건수',
       '1km초과3km이하배달건수', '3km초과5km이하배달건수', '거리 5000이상', '한식_매장수', '분식_매장수',
       '카페/디저트_매장수', '돈까스/일식_매장수', '회_매장수', '치킨_매장수', '피자_매장수', '아시안/양식_매장수',
       '중식_매장수', '족발/보쌈_매장수', '야식_매장수', '찜탕_매장수', '도시락_매장수', '패스트푸드_매장수'],
      dtype='object')

KGUINSCTNORDR
(54754, 7)
Index(['년도', '월', '배달상점 업종명', '배달상점 광역시도명', '배달상점 시군구명', '배달거리 구간명', '배달주문수'], dtype='object')

KGUWTHRDLVRDF
(380741, 27)
Index(['광역시도명', '시군구명', '날짜', '시간대별 시간', '강수 유형명', '습도값', '강수량 값', '기온값',
       '풍속값', '바람강도 유형명', '동쪽서쪽바람유형명', '풍향값', '풍향카테고리명', '한식_배달건수', '분식_배달건수',
       '카페/디저트_배달건수', '돈까스/일식_배달건수', '회_배달건수', '치킨_배달건수', '피자_배달건수',
       '아시안/양식_배달건수', '중식_배달건수', '족발/보쌈_배달건수', '야식_배달건수', '찜탕_배달건수',
       '도시락_배달건수', '패스트푸드_배달건수'],
      dtype='object')

KGUDLIVERYSTORE00001
(83159, 11)
Index(['배달상점ID', '배달상점 업종명', '배달상점 법정동코드', '배달상점 시도명', '배달상점 시군구명',
       '배달상점 법정동 읍면동명', '배달상점 법정동 리명', '배달상점 행정동코드', '배달상점 행정동 읍면동명',
       '배달상점 도로명주소코드', '배달상점 도로명주소 도로명'],
      dtype='object')

## 파일로 저장

In [48]:
for i, (name, ls) in enumerate(all_dict.items()):
    # print(name)
    code = ls[0]
    cols = ls[1]
    print(i, name, code)
    concat_dff_dict[code].to_csv(f'type_data/{name}.csv', index=False)

0 날씨별 배달 품목차이 KGUWTHRDLVRDF
1 지역-업종 배달평균거리 KGUAREAAVDSTN
2 배달 상점 데이터 KGUDLIVERYSTORE00001
3 업종 목적지별 배달 주문건수 KGUDSTNORDER
4 업종-거리구간 배달 건수 KGUINSCTNORDR
5 업종 목적지별 평균주문금액 KGUDSTNAMOUNT
6 주문지역 주거 특성 KGURESIDEINFO
7 주문지역 상권유형 특성 KGUTRDARINFO
8 주문지역 인구 특성 KGUPOPLTNINFO
9 주문지역 기상 정보 KGUWETHERINFO
10 지역-업종 결제정보 KGUAREAINDPAY
11 지역-요일 배달 품목정보 KGUAREADOITEM
12 업종-거리구간 상권 정보 KGUINSCTNINFO
13 시간-지역별 배달 주문건수 KGUTIMEORDER
14 시간-지역별 배달 평균주문금액 KGUTIMEAMOUNT
15 시간-지역별 배달 소요시간평균 KGUTIMEDLVR
16 업종-지역별 평균주문금액 KGUINDTAMOUNT
17 업종-지역별 배달 주문건수 KGUINDTORDER
18 업종-지역별 평균배달소요시간 KGUINDTDLVR

In [49]:
DataBase_info = {}
for name, ls in tqdm(all_dict.items()):
    # print(name)
    code = ls[0]
    cols = ls[1]
    dff = concat_dff_dict[code]
    info = {'name': name,
           'code': code,
           'len': len(dff),
           'columns': list(dff.columns),
           'shape': dff.shape}
    DataBase_info[name] = info

100%|██████████| 19/19 [00:00<00:00, 6350.95it/s]

In [50]:
with open('Database_info.p', 'wb') as file:    # james.p 파일을 바이너리 쓰기 모드(wb)로 열기
    pickle.dump(DataBase_info, file)

In [51]:
DataBase = {}
for name, ls in tqdm(all_dict.items()):
    # print(name)
    code = ls[0]
    cols = ls[1]
    dff = concat_dff_dict[code]
    info = {'name': name,
           'code': code,
           'len': len(dff),
           'columns': list(dff.columns),
           'shape': dff.shape}
    DataBase[name] = {'info': info, 'data': dff}

100%|██████████| 19/19 [00:00<00:00, 12202.08it/s]

In [52]:
with open('Database.p', 'wb') as file:    # james.p 파일을 바이너리 쓰기 모드(wb)로 열기
    pickle.dump(DataBase, file)