In [9]:
import pandas as pd
from sklearn.svm import SVC
import numpy as np
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')
import pickle
import matplotlib.pyplot as plt

In [10]:
data=pd.read_csv('diabetes.csv')

In [11]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
data.info()

In [ ]:
data.describe()

In [12]:
data = np.array([0, None])

In [13]:
data

array([0, None], dtype=object)

In [3]:
col_list = ['Glucose', 'BloodPressure' ,'SkinThickness' ,'Insulin' ,'BMI']
for i in col_list :
    for j in data[data[i]==0].index :
        np.where(data.loc[j][i]==0, None, data.loc[j][i])

In [4]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
data[['Glucose', 'BloodPressure' ,'SkinThickness' ,'Insulin' ,'BMI']]=data[['Glucose', 'BloodPressure' ,'SkinThickness', 'Insulin', 'BMI']].replace(0, None)

In [ ]:
data.isnull().sum()

col_name =['Pregnancies',	'Glucose',	'BloodPressure'	,'SkinThickness'	,'Insulin'	,'BMI'	,'DiabetesPedigreeFunction'	,'Age']	
for col in col_name :
    data[data[col] == 0][col].replace(0, None, inplace=True) 안되는이유??

In [ ]:
data['Pregnancies']

/ 1 // 2 // 34 // 56 // 789 // 10+

In [ ]:
data['Pregnancies2']=np.where(data['Pregnancies']==0, 0,
                     np.where(data['Pregnancies']==1, 1,
                     np.where(data['Pregnancies']==2, 2,
                     np.where(data['Pregnancies'] <5, 3,
                     np.where(data['Pregnancies'] <7, 4,
                     np.where(data['Pregnancies'] <10, 5, 6))))))

In [ ]:
data.isnull().sum()

In [ ]:
data[['Glucose', 'BloodPressure' ,'SkinThickness' ,'Insulin' ,'BMI']].fillna(data.groupby('Pregnancies2')[['Glucose', 'BloodPressure' ,'SkinThickness' ,'Insulin' ,'BMI']].transform('median'),inplace=True)

In [ ]:
data

In [ ]:
col_list=['Glucose', 'BloodPressure' ,'SkinThickness' ,'Insulin' ,'BMI']
for col in col_list :
    data[col].fillna(data.groupby('Pregnancies2')[col].transform('median'), inplace=True)

In [ ]:
data